name: Build

on:
  push:
    branches:
      - main

jobs:
  tox:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v5
      #   if: ${{ env.CODECOV_TOKEN != '' }}
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     token: ${{ env.CODECOV_TOKEN }}
      #     slug: ardaaras99/trial-project

  bump-version:
    needs: tox
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    env:
      # !! IMPORTANT !!
      # Here PERSONAL_ACCESS_TOKEN is set to GITHUB_TOKEN, this is usually fine,
      # but when you use the repository's GITHUB_TOKEN to perform tasks, events
      # triggered by the GITHUB_TOKEN will not create a new workflow run. This
      # prevents you from accidentally creating recursive workflow runs. You
      # will want to configure a GitHub Actions secret with a Personal Access
      # Token if you want GitHub Actions CI checks to run on releases, such as
      # publishing to PyPI. Set PERSONAL_ACCESS_TOKEN secret and use the
      # following line instead of the one below it:
      #
      # PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ env.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}
